spring.application.name=product-service
server.port=8081

# R2DBC H2 DATABASE
spring.r2dbc.url=r2dbc:h2:mem:///productdb
spring.r2dbc.username=sa
spring.r2dbc.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always

logging.level.root=INFO
logging.level.com.company.product=DEBUG

springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=*