server:
  port: 8082

spring:
  application:
    name: cart-service

  r2dbc:
    url: r2dbc:h2:mem:///cartdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    com.company.cart: DEBUG
    org.springframework.r2dbc: DEBUG

product:
  service:
    base-url: http://PRODUCT-SERVICE

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  swagger-ui:
    path: /swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}